export const villes = [
    { slug: "paris", name: "Paris", quartiers: ["Montmartre", "Bastille", "Champs-Élysées"] },
    { slug: "marseille", name: "Marseille", quartiers: ["Vieux-Port", "La Joliette", "Le Panier"] },
    { slug: "lyon", name: "Lyon", quartiers: ["Part-Dieu", "Croix-Rousse", "Presqu'île"] },
    { slug: "toulouse", name: "Toulouse", quartiers: ["Capitole", "Carmes", "Saint-Cyprien"] },
    { slug: "nice", name: "Nice", quartiers: ["Vieux-Nice", "Libération", "Cimiez"] },
    { slug: "nantes", name: "Nantes", quartiers: ["Centre-Ville", "Parc de la Toussaint", "Parc de la Source"] },
    { slug: "montpellier", name: "Montpellier", quartiers: ["Écusson", "Port Marianne", "Celleneuve"] },
    { slug: "strasbourg", name: "Strasbourg", quartiers: ["Centre-Ville", "Krutenau", "Neudorf"] },
    { slug: "bordeaux", name: "Bordeaux", quartiers: ["Chartrons", "Saint-Michel", "Caudéran"] },
    { slug: "lille", name: "Lille", quartiers: ["Vieux-Lille", "Wazemmes", "Moulins"] },
    { slug: "rennes", name: "Rennes", quartiers: ["Centre-Ville", "Villejean", "Maurepas"] },
    { slug: "le-havre", name: "Le Havre", quartiers: ["Le Havre", "Les Docks", "La Plage"] },
    { slug: "reims", name: "Reims", quartiers: ["Centre-Ville", "Cernay", "La Neuvillette"] },
    { slug: "toulon", name: "Toulon", quartiers: ["Centre-Ville", "Le Mourillon", "La Seyne-sur-Mer"] },
    { slug: "saint-etienne", name: "Saint-Étienne", quartiers: ["Centre-Ville", "Montplaisir", "Cité du Design"] },
    { slug: "le-mans", name: "Le Mans", quartiers: ["Centre-Ville", "Pats", "Gazonfier"] },
    { slug: "aix-en-provence", name: "Aix-en-Provence", quartiers: ["Centre-Ville", "Les Milles", "Peyrolles"] },
    { slug: "clermont-ferrand", name: "Clermont-Ferrand", quartiers: ["Centre-Ville", "Montjuzet", "Fontgiève"] },
    { slug: "angers", name: "Angers", quartiers: ["Centre-Ville", "La Doutre", "Monplaisir"] },
    { slug: "villeurbanne", name: "Villeurbanne", quartiers: ["Charpennes", "La Croix-Luizet", "Gratte-Ciel"] },
    { slug: "le-puy-en-velay", name: "Le Puy-en-Velay", quartiers: ["Centre-Ville", "Saint-Jean", "Les Capucins"] },
    { slug: "metz", name: "Metz", quartiers: ["Centre-Ville", "Grange-aux-Belles", "Plantières"] },
    { slug: "brest", name: "Brest", quartiers: ["Centre-Ville", "Saint-Pierre", "Recouvrance"] },
    { slug: "caen", name: "Caen", quartiers: ["Centre-Ville", "Vaugueux", "Saint-Jean"] },
    { slug: "chambery", name: "Chambéry", quartiers: ["Centre-Ville", "Challes-les-Eaux", "Montagnole"] },
    { slug: "antibes", name: "Antibes", quartiers: ["Vieil Antibes", "Juan-les-Pins", "La Fontonne"] },
    { slug: "perpignan", name: "Perpignan", quartiers: ["Centre-Ville", "Saint-Assiscle", "Le Soler"] },
    { slug: "tours", name: "Tours", quartiers: ["Centre-Ville", "Les Halles", "Vieux-Tours"] },
    { slug: "orleans", name: "Orléans", quartiers: ["Centre-Ville", "La Source", "Saint-Jean"] },
    { slug: "valence", name: "Valence", quartiers: ["Centre-Ville", "Fontbarlettes", "Châteauvert"] },
    { slug: "nimes", name: "Nîmes", quartiers: ["Centre-Ville", "Les Hauts de Nîmes", "La Placette"] },
    { slug: "cannes", name: "Cannes", quartiers: ["La Croisette", "Le Suquet", "Carnot"] },
    { slug: "dijon", name: "Dijon", quartiers: ["Centre-Ville", "Grésilles", "Fontaine d'Ouche"] },
    { slug: "grenoble", name: "Grenoble", quartiers: ["Centre-Ville", "Saint-Bruno", "Bastille"] },
    { slug: "limoges", name: "Limoges", quartiers: ["Centre-Ville", "La Bastide", "Beaubreuil"] },
    { slug: "amiens", name: "Amiens", quartiers: ["Centre-Ville", "Saint-Leu", "Henriville"] },
    { slug: "besancon", name: "Besançon", quartiers: ["Centre-Ville", "Battant", "Planoise"] },
    { slug: "annecy", name: "Annecy", quartiers: ["Vieil Annecy", "Cran-Gevrier", "Seynod"] },
    { slug: "poitiers", name: "Poitiers", quartiers: ["Centre-Ville", "Saint-Cyprien", "Les Couronneries"] },
    { slug: "mulhouse", name: "Mulhouse", quartiers: ["Centre-Ville", "Rebberg", "Dornach"] },
    { slug: "rouen", name: "Rouen", quartiers: ["Centre-Ville", "Saint-Sever", "Jardin des Plantes"] },
    { slug: "avignon", name: "Avignon", quartiers: ["Centre-Ville", "La Balance", "Monclar"] },
    { slug: "bayonne", name: "Bayonne", quartiers: ["Grand Bayonne", "Petit Bayonne", "Saint-Esprit"] },
    { slug: "la-rochelle", name: "La Rochelle", quartiers: ["Vieux Port", "Tasdon", "Mireuil"] },
    { slug: "calais", name: "Calais", quartiers: ["Centre-Ville", "Beau Marais", "Fort Nieulay"] },
    { slug: "argeles-sur-mer", name: "Argelès-sur-Mer", quartiers: ["Centre-Ville", "Le Racou", "Valmy"] },
    { slug: "biarritz", name: "Biarritz", quartiers: ["Grande Plage", "Port Vieux", "Milady"] },
    { slug: "carcassonne", name: "Carcassonne", quartiers: ["Cité Médiévale", "La Bastide", "Gambetta"] },
    { slug: "colmar", name: "Colmar", quartiers: ["Petite Venise", "Centre-Ville", "Saint-Joseph"] },
    { slug: "dunkerque", name: "Dunkerque", quartiers: ["Centre-Ville", "Malo-les-Bains", "Rosendaël"] },
    { slug: "evian-les-bains", name: "Évian-les-Bains", quartiers: ["Centre-Ville", "Les Hauts", "Amphion"] },
    { slug: "fontainebleau", name: "Fontainebleau", quartiers: ["Centre-Ville", "Les Aigles", "La Faisanderie"] },
    { slug: "honfleur", name: "Honfleur", quartiers: ["Vieux Bassin", "Enclos", "Sainte-Catherine"] },
    { slug: "la-baule", name: "La Baule", quartiers: ["Centre-Ville", "Les Salines", "Pornichet"] },
    { slug: "le-touquet", name: "Le Touquet", quartiers: ["Centre-Ville", "Quentovic", "Canche"] },
    { slug: "menton", name: "Menton", quartiers: ["Vieille Ville", "Garavan", "Borrigo"] },
    { slug: "saint-malo", name: "Saint-Malo", quartiers: ["Intra-Muros", "Paramé", "Rothéneuf"] },
    { slug: "saint-tropez", name: "Saint-Tropez", quartiers: ["Vieux Port", "La Ponche", "Les Salins"] },
    { slug: "sarlat", name: "Sarlat", quartiers: ["Centre Historique", "La Madeleine", "Terre-Neuve"] },
    { slug: "sete", name: "Sète", quartiers: ["Centre-Ville", "Quartier Haut", "Les Pierres Blanches"] },
    { slug: "vannes", name: "Vannes", quartiers: ["Intra-Muros", "Saint-Patern", "Ménimur"] },
    { slug: "versailles", name: "Versailles", quartiers: ["Centre-Ville", "Notre-Dame", "Montreuil"] },
];