export const villes = [
    { slug: "paris", nom: "Paris", quartiers: ["Montmartre", "Bastille", "Champs-Élysées"] },
    { slug: "marseille", nom: "Marseille", quartiers: ["Vieux-Port", "La Joliette", "Le Panier"] },
    { slug: "lyon", nom: "Lyon", quartiers: ["Part-Dieu", "Croix-Rousse", "Presqu'île"] },
    { slug: "toulouse", nom: "Toulouse", quartiers: ["Capitole", "Carmes", "Saint-Cyprien"] },
    { slug: "nice", nom: "Nice", quartiers: ["Vieux-Nice", "Libération", "Cimiez"] },
    { slug: "nantes", nom: "Nantes", quartiers: ["Centre-Ville", "Parc de la Toussaint", "Parc de la Source"] },
    { slug: "montpellier", nom: "Montpellier", quartiers: ["Écusson", "Port Marianne", "Celleneuve"] },
    { slug: "strasbourg", nom: "Strasbourg", quartiers: ["Centre-Ville", "Krutenau", "Neudorf"] },
    { slug: "bordeaux", nom: "Bordeaux", quartiers: ["Chartrons", "Saint-Michel", "Caudéran"] },
    { slug: "lille", nom: "Lille", quartiers: ["Vieux-Lille", "Wazemmes", "Moulins"] },
    { slug: "rennes", nom: "Rennes", quartiers: ["Centre-Ville", "Villejean", "Maurepas"] },
    { slug: "le-havre", nom: "Le Havre", quartiers: ["Le Havre", "Les Docks", "La Plage"] },
    { slug: "reims", nom: "Reims", quartiers: ["Centre-Ville", "Cernay", "La Neuvillette"] },
    { slug: "toulon", nom: "Toulon", quartiers: ["Centre-Ville", "Le Mourillon", "La Seyne-sur-Mer"] },
    { slug: "saint-etienne", nom: "Saint-Étienne", quartiers: ["Centre-Ville", "Montplaisir", "Cité du Design"] },
    { slug: "le-mans", nom: "Le Mans", quartiers: ["Centre-Ville", "Pats", "Gazonfier"] },
    { slug: "aix-en-provence", nom: "Aix-en-Provence", quartiers: ["Centre-Ville", "Les Milles", "Peyrolles"] },
    { slug: "clermont-ferrand", nom: "Clermont-Ferrand", quartiers: ["Centre-Ville", "Montjuzet", "Fontgiève"] },
    { slug: "angers", nom: "Angers", quartiers: ["Centre-Ville", "La Doutre", "Monplaisir"] },
    { slug: "villeurbanne", nom: "Villeurbanne", quartiers: ["Charpennes", "La Croix-Luizet", "Gratte-Ciel"] },
    { slug: "le-puy-en-velay", nom: "Le Puy-en-Velay", quartiers: ["Centre-Ville", "Saint-Jean", "Les Capucins"] },
    { slug: "metz", nom: "Metz", quartiers: ["Centre-Ville", "Grange-aux-Belles", "Plantières"] },
    { slug: "brest", nom: "Brest", quartiers: ["Centre-Ville", "Saint-Pierre", "Recouvrance"] },
    { slug: "caen", nom: "Caen", quartiers: ["Centre-Ville", "Vaugueux", "Saint-Jean"] },
    { slug: "chambery", nom: "Chambéry", quartiers: ["Centre-Ville", "Challes-les-Eaux", "Montagnole"] },
    { slug: "antibes", nom: "Antibes", quartiers: ["Vieil Antibes", "Juan-les-Pins", "La Fontonne"] },
    { slug: "perpignan", nom: "Perpignan", quartiers: ["Centre-Ville", "Saint-Assiscle", "Le Soler"] },
    { slug: "tours", nom: "Tours", quartiers: ["Centre-Ville", "Les Halles", "Vieux-Tours"] },
    { slug: "orleans", nom: "Orléans", quartiers: ["Centre-Ville", "La Source", "Saint-Jean"] },
    { slug: "valence", nom: "Valence", quartiers: ["Centre-Ville", "Fontbarlettes", "Châteauvert"] },
    { slug: "nîmes", nom: "Nîmes", quartiers: ["Centre-Ville", "Les Hauts de Nîmes", "La Placette"] },
    { slug: "cannes", nom: "Cannes", quartiers: ["La Croisette", "Le Suquet", "Carnot"] },
];