export const villes = [
    { slug: "paris", name: "Paris", quartiers: ["Montmartre", "Bastille", "Champs-Élysées"] },
    { slug: "marseille", name: "Marseille", quartiers: ["Vieux-Port", "La Joliette", "Le Panier"] },
    { slug: "lyon", name: "Lyon", quartiers: ["Part-Dieu", "Croix-Rousse", "Presqu'île"] },
    { slug: "toulouse", name: "Toulouse", quartiers: ["Capitole", "Carmes", "Saint-Cyprien"] },
    { slug: "nice", name: "Nice", quartiers: ["Vieux-Nice", "Libération", "Cimiez"] },
    { slug: "nantes", name: "Nantes", quartiers: ["Centre-Ville", "Parc de la Toussaint", "Parc de la Source"] },
    { slug: "montpellier", name: "Montpellier", quartiers: ["Écusson", "Port Marianne", "Celleneuve"] },
    { slug: "strasbourg", name: "Strasbourg", quartiers: ["Centre-Ville", "Krutenau", "Neudorf"] },
    { slug: "bordeaux", name: "Bordeaux", quartiers: ["Chartrons", "Saint-Michel", "Caudéran"] },
    { slug: "lille", name: "Lille", quartiers: ["Vieux-Lille", "Wazemmes", "Moulins"] },
    { slug: "rennes", name: "Rennes", quartiers: ["Centre-Ville", "Villejean", "Maurepas"] },
    { slug: "le-havre", name: "Le Havre", quartiers: ["Le Havre", "Les Docks", "La Plage"] },
    { slug: "reims", name: "Reims", quartiers: ["Centre-Ville", "Cernay", "La Neuvillette"] },
    { slug: "toulon", name: "Toulon", quartiers: ["Centre-Ville", "Le Mourillon", "La Seyne-sur-Mer"] },
    { slug: "saint-etienne", name: "Saint-Étienne", quartiers: ["Centre-Ville", "Montplaisir", "Cité du Design"] },
    { slug: "le-mans", name: "Le Mans", quartiers: ["Centre-Ville", "Pats", "Gazonfier"] },
    { slug: "aix-en-provence", name: "Aix-en-Provence", quartiers: ["Centre-Ville", "Les Milles", "Peyrolles"] },
    { slug: "clermont-ferrand", name: "Clermont-Ferrand", quartiers: ["Centre-Ville", "Montjuzet", "Fontgiève"] },
    { slug: "angers", name: "Angers", quartiers: ["Centre-Ville", "La Doutre", "Monplaisir"] },
    { slug: "villeurbanne", name: "Villeurbanne", quartiers: ["Charpennes", "La Croix-Luizet", "Gratte-Ciel"] },
    { slug: "le-puy-en-velay", name: "Le Puy-en-Velay", quartiers: ["Centre-Ville", "Saint-Jean", "Les Capucins"] },
    { slug: "metz", name: "Metz", quartiers: ["Centre-Ville", "Grange-aux-Belles", "Plantières"] },
    { slug: "brest", name: "Brest", quartiers: ["Centre-Ville", "Saint-Pierre", "Recouvrance"] },
    { slug: "caen", name: "Caen", quartiers: ["Centre-Ville", "Vaugueux", "Saint-Jean"] },
    { slug: "chambery", name: "Chambéry", quartiers: ["Centre-Ville", "Challes-les-Eaux", "Montagnole"] },
    { slug: "antibes", name: "Antibes", quartiers: ["Vieil Antibes", "Juan-les-Pins", "La Fontonne"] },
    { slug: "perpignan", name: "Perpignan", quartiers: ["Centre-Ville", "Saint-Assiscle", "Le Soler"] },
    { slug: "tours", name: "Tours", quartiers: ["Centre-Ville", "Les Halles", "Vieux-Tours"] },
    { slug: "orleans", name: "Orléans", quartiers: ["Centre-Ville", "La Source", "Saint-Jean"] },
    { slug: "valence", name: "Valence", quartiers: ["Centre-Ville", "Fontbarlettes", "Châteauvert"] },
    { slug: "nîmes", name: "Nîmes", quartiers: ["Centre-Ville", "Les Hauts de Nîmes", "La Placette"] },
    { slug: "cannes", name: "Cannes", quartiers: ["La Croisette", "Le Suquet", "Carnot"] },
];